
server:
  port: 8090
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
#视图解析器配置  只有视图解析器不一样
  mvc:       
    view:
      prefix: /WEB-INF/    
      suffix: .jsp
 # /默认代表根目录 src/main/webapp   

 #数据库配置
mybatis: 
  mapper-locations:
  - classpath:/mybatis/mappers/*.xml

#log 打印日志
logging:
  level:
    com.per: debug